### PR TITLE
Cuda fallback optimization

### PR DESCRIPTION
**Pull request by Sing303**
Now if you specify [Cuda, Vulcan]. It will try to find Cuda, if it doesn't find it, it will use CPU. This edit fixes this problem and if Cuda is not found, the next in priority will be called

### CODE REVIEW

**Comment by Sing303** [comment]
@sandrohanea please check this PR

**Comment by sandrohanea** [comment]
Thanks for reporting the bug and proposing a fix!

The problem that I see with this approach is that it introduces a dependency on `ManagedCuda` even for people that won't use Cuda at all. 

Another problem is that `ManagedCuda` is a ` GNU LESSER GENERAL PUBLIC LICENSE` package, which is incompatible with this one (MIT). 

I understand the issue and I think we should try to identify if Cuda device is available before loading the Cuda runtime, but I believe we can do this without introducing this dependency.

Also, I wouldn't replace the Cuda Library from RuntimeOption with CPU runtime, but just skip cuda loading. If the client wants the fallback to CPU, it should either allow the default Order or define: [Cuda, Vulcan, Cpu].

**Comment by Sing303** [comment]
An important opportunity, I'll see what else I can come up with.

**Comment by sandrohanea** [comment]
It will be probably superseded by https://github.com/sandrohanea/whisper.net/pull/225

**Pull request closed without merging**
